stages:
  # Download Reddit comments data
  download_comments:
    foreach: ${reddit_comments}
    do:
      cmd: curl https://files.pushshift.io/reddit/comments/RC_${item}.zst | unzstd --long=31 | bzip2 > data/raw_data/comments/RC_${item}.bz2
      outs:
        - data/raw_data/comments/RC_${item}.bz2


  download_submissions:
    foreach: ${reddit_submissions}
    do:
      cmd: curl https://files.pushshift.io/reddit/submissions/RS_${item}.zst | unzstd --long=31 | bzip2 > data/raw_data/submissions/RS_${item}.bz2
      outs:
        - data/raw_data/submissions/RS_${item}.bz2

