name: ihop
channels:
  - defaults
  - plotly
dependencies:
  - gensim=4.1.2
  - jupyter=1.0.0
  - numpy=1.21.2
  - pandas=1.3.4
  - pip=21.2.4
  - pip:
    - pyspark==3.2.0
  - plotly==5.5.0
  - pytimeparse==1.1.8
  - scikit-learn==1.0.1
  - seaborn=0.11.2