months:
  - 2021-04
# - 2021-05
#  - 2021-06

# Parameters to the ihop.import_data c2v script
community2vec_data_prep:
  top_n: 10000
  exclude_top_users: 0.05

# Parameters to the ihop.community2vec script
community2vec_params:
  # Hyperparameters to tune against for getting the best analogy accuracy
  param_grid: "'{\"alpha\": [0.05, 0.01], \"vector_size\":[100, 150, 300], \"sample\":[0.005, 0.05], \"negative\":[20,40]}'"
  # How many epochs to train each model for?
  epochs: 5
  # How many workers to use for training the model?
  workers: 3

# Configure directories to store experiment results in
comments_dir: data/raw_data/comments
submissions_dir: data/raw_data/submissions
community2vec_dir: data/community2vec