months:
  - 2021-04
# - 2021-05
#  - 2021-06

community2vec_data_prep:
  top_n: 10000
  exclude_top_users: 0.05

community2vec_params:
  param_grid: "'{\"alpha\": [0.05, 0.01], \"vector_size\":[100, 150, 300], \"sample\":[0.005, 0.05], \"negative\":[20,40]}'"
  epochs: 5

# Configure directories to store experiment results in
comments_dir: data/raw_data/comments
submissions_dir: data/raw_data/submissions
community2vec_dir: data/community2vec